### PR TITLE
Fix win2012r2 support

### LINKED ISSUE #81: Installing vagrant returns non-zero and indicates failure on the first try.
Discovered in release testing.
On a windows server without vagrant the cookbook reports that the install fails on the first run.
Ran vagrant plugin list returned -1073741515
       [2018-04-02T05:21:28+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: vagrant_plugin[vagrant-ohai] (vagrant::install_plugins line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '-1073741515'
       ---- Begin output of vagrant plugin list ----
Even though vagrant is actually installed.

### PR DESCRIPTION
**Pull request by rjhornsby**
Fixes for Windows 2012R2:

* The Vagrant installer needs to reboot windows, but the MSI does this in a way that chef can't handle. As an alternative, we make chef interrupt itself and reboot the instance.
* Related to the above, the MSI returns two specific exit codes when it finishes (but not `0`...) that chef needs to know about.
* Vagrant version 1.9.7 suffers from the issue described in #82 (`Expected process to exit with [0], but received '-1073741515'`). For unknown reasons, this problem is resolved by using 2.0.3 (Perhaps also earlier versions, but they were not tested.)
* Elevating privileges (in `execute_cli()`) would be the logical thing to do -- it makes sense. For some reason, this leads Windows to complain that the vagrant user doesn't have two specific NT rights. Adding those rights does not resolve the complaint. Dropping the request to elevate privileges _does_ seem to resolve it.
* It's hard to tell exactly what's going on, but the environment variable `VAGRANT_HOME` appears to confuse Vagrant into installing plugins into locations where Vagrant doesn't see them (`vagrant plugin list`). Dropping this environment variable resolves the issue.

Resolves #81 and #82

### CODE REVIEW

File: recipes/windows.rb [hunk 1]
```diff
@@ -24,4 +24,13 @@
   version vagrant_version
   source vagrant_url
   checksum vagrant_checksum
+  returns [1641, 3010]
```
Comment (MarkGibbons) [inline recipes/windows.rb]: Random OK return values from the MSI install.

File: attributes/default.rb [hunk 2]
```diff
@@ -19,7 +19,7 @@
 
 return unless %w(darwin windows linux).include?(node['os'])
 
-default['vagrant']['version']     = '1.9.7'
+default['vagrant']['version']     = '2.0.3'
```
Comment (MarkGibbons) [inline attributes/default.rb]: 2.0.3 was planned for the next version. Cool.  Folks told me 1.9.7 had issues and was likely the cause of most of the install problems.

**Comment by MarkGibbons** [comment]
I've got a brand new windows box that I'll test this on. Thank you very much.

File: recipes/windows.rb (hunk 1 above)
Comment (rjhornsby) [reply recipes/windows.rb]: Yeah. Windows is kind of a cluster ~~when it comes to exit codes~~. It's unpredictable from one thing to the next what means `success` and what means `failure`. Worse, because the exit code value is not limited to just 1 byte (0-255), in practical terms it could be basically anything.
